SELECT_BASE_COST = 50
ROW_PROCESSING_COST = 2
TABLE_SCAN_COST_PER_ROW = 5
OPERATOR_COST_PER_ROW = 2

DEFAULT_ROW_ESTIMATE = 1000
DEFAULT_SELECTIVITY = 0.1
JOIN_SELECTIVITY = 0.1

NESTED_LOOP_JOIN_FACTOR = 1
HASH_JOIN_BASE_COST = 1000
HASH_JOIN_COST_PER_ROW = 3
